version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'yarn run dev --host 0.0.0.0'
    ports:
      - 4321:4321
    volumes:
      - node_modules:/app/node_modules
    tty: true
    stdin_open: true
    environment:
      - ASTRO_TELEMETRY_DISABLED=1
      - CHOKIDAR_USEPOLLING=true
volumes:
  node_modules:
