version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: "yarn run develop --host=0.0.0.0"
    ports:
      - 8000:8000
    volumes:
      - node_modules:/app/node_modules
    tty: true
    stdin_open: true
    environment:
      - GATSBY_TELEMETRY_DISABLED=1
      - CHOKIDAR_USEPOLLING=true
volumes:
  node_modules:
