version: '3.7'
services:
  server:
    build: .
    volumes:
      - .:/home/app
    ports:
      - 127.0.0.1:8000:8000
    entrypoint: "yarn run develop --host=0.0.0.0"
  code:
    image: codercom/code-server
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./:/home/coder/app
    entrypoint: "code-server --auth none /home/coder/app"
