version: '3.7'
services:
  server:
    build: .
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    ports:
      - 127.0.0.1:8000:8000
    entrypoint: "yarn run develop --host=0.0.0.0"
volumes:
  node_modules:
